/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, September 20, 2017 at 10:03:53 PM Eastern European Summer Time
* Operating System: Version 11.0 (Build 15A372)
* Image Source: /System/Library/PrivateFrameworks/ClockKitUI.framework/ClockKitUI
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/

#import <ClockKitUI/CLKUIResourceManager.h>

@protocol MTLDevice, MTLLibrary;
@class NSMutableDictionary;

@interface CLKUIMetalResourceManager : CLKUIResourceManager {

	<MTLDevice>* _device;
	<MTLLibrary>* _library;
	NSMutableDictionary* _functionsByName;

}
+(id)functionWithName:(id)arg1 ;
+(id)sharedLibrary;
+(id)sharedDevice;
+(id)sharedMetalInstance;
-(id)init;
-(void).cxx_destruct;
-(id)_newTextureForUuid:(id)arg1 ;
-(void)_purgeTextures:(id)arg1 ;
@end

