clean: true
output: docs
theme: fullwidth
objc: true
sdk: iphonesimulator
module: Cephei
umbrella_header: JazzyUmbrella.h
framework_root: .theos/_/usr/lib
author: HASHBANG Productions
author_url: https://hbang.github.io/
github_url: https://github.com/hbang/libcephei
root_url: https://hbang.github.io/libcephei/
dash_url: https://hbang.github.io/libcephei/docsets/Cephei.xml
readme: README.md
documentation: info/*.md
exclude: "*/include/*"
hide_documentation_coverage: true

custom_categories:
  - name: "Cephei — General"
    children:
      - "Container Support"
      - HBOutputForShellCommand
      - HBOutputForShellCommandWithReturnCode
      - HBPreferences
      - HBRespringController
      - NSDictionary(HBAdditions)
      - NSLayoutConstraint(CompactConstraint)
      - NSString(HBAdditions)
      - UIColor(HBAdditions)
      - UIView(CompactConstraint)
  
  - name: "Cephei — Types/Constants"
    children:
      - HBPreferencesDidChangeNotification
      - HBPreferencesNotMobileException
      - HBPreferencesChangeCallback
      - HBPreferencesValueChangeCallback

  - name: "CepheiPrefs — General"
    children:
      - "CepheiPrefs Annoying Warning"
      - HBAppearanceSettings
      - HBSupportController

  - name: "CepheiPrefs — List Controllers"
    children:
      - HBAboutListController
      - HBListController
      - HBRootListController
      - PSListController(HBTintAdditions)

  - name: "CepheiPrefs — Cells"
    children:
      - HBDiscreteSliderTableCell
      - HBImageTableCell
      - HBLinkTableCell
      - HBPackageTableCell
      - HBPackageNameHeaderCell
      - HBSpinnerTableCell
      - HBStepperTableCell
      - HBTintedTableCell
      - HBTwitterCell

  - name: "CepheiPrefs — Deprecated"
    children:
      - HBListItemsController
      - HBInitialsLinkTableCell
