@interface Excitant : NSObject
+(void)AUXtoggleFlash;
+(void)AUXtoggleLPM;
+(void)AUXtoggleAirplaneMode;
+(void)AUXtoggleMute;
+(void)AUXtoggleRotationLock;
+(void)AUXcontrolCenter;
+(void)AUXrespring;
+(void)AUXlaunchApp:(id)arg1;
+(void)AUXlockDevice;
+(void)AUXhomePress;
+(BOOL)AUXisDeviceLocked;
+(void)AUXtoggleBluetooth;
+(BOOL)AUXisDeviceOnSB;
+(BOOL)AUXisDeviceOnNC;
+(void)AUXtoggleWiFi;
+(void)AUXreboot;
+(void)AUXshutdown;
+(void)AUXtoggleReachability;
+(void)AUXtakeScreenshot;
+(void)AUXtoggleAppSwitcher;
+(void)AUXcallSiri;
+(void)AUXtoggleNC;
@end